version: "3.9"

volumes:
  pgdata:
  static_volume:

services:
  backend:
    build: .
    container_name: backend_django_app
    volumes:
      - static_volume:/code/static
    command: sh -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - postgredb
  postgredb:
    image: postgres
    container_name: postgredb
    restart: unless-stopped
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    volumes:
      - static_volume:/code/static
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    depends_on:
      - backend